[package]
name = "libsieve-rs"
version = "0.1.0"
authors = ["Brennan Vincent <brennan@umanwizard.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
failure_derive = "0.1"
itertools = "0.8"
memmem = "0.1.1"
nom = "5.0.1"
regex = "1.3"
regex-syntax = "0.6"
